# Generated by Django 6.1 on 2026-09-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculoElectrico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('bateria_kwh', models.DecimalField(decimal_places=2, max_digits=6)),
                ('autonomia_km', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tiempo_carga_10_80_min', models.PositiveIntegerField()),
            ],
        ),
    ]
