# Generated by Django 6.1 on 2026-09-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electromovilidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculoelectrico',
            name='detalle_carga',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculoelectrico',
            name='tiempo_carga_10_80_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
