# Generated by Django 6.1 on 2026-09-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargadorElectrico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=150, null=True)),
                ('provincia', models.CharField(blank=True, max_length=150, null=True)),
                ('comuna', models.CharField(blank=True, max_length=150, null=True)),
                ('tipo_ubicacion', models.CharField(blank=True, max_length=150, null=True)),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('conectores_publicados', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_conector', models.CharField(blank=True, max_length=200, null=True)),
                ('potencia_kw', models.CharField(blank=True, max_length=100, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('fuente_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('fuente_url', models.URLField(blank=True, max_length=500, null=True)),
                ('estado_revision', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
